FROM anapsix/alpine-java
MAINTAINER Vladimir Cvetanovic <cvetanovic9696@gmail.com>
ADD target/api-gateway-0.0.1-SNAPSHOT.jar api-gateway.jar
ENTRYPOINT ["java", "-jar", "/api-gateway.jar"]
EXPOSE 8440