FROM anapsix/alpine-java
MAINTAINER Vladimir Cvetanovic <cvetanovic9696@gmail.com>
ADD target/bank-service-0.0.1-SNAPSHOT.jar bank-service.jar
ENTRYPOINT ["java", "-jar", "/bank-service.jar"]
EXPOSE 8442