FROM anapsix/alpine-java
MAINTAINER Vladimir Cvetanovic <cvetanovic9696@gmail.com>
ADD target/bitcoin-service-0.0.1-SNAPSHOT.jar bitcoin-service.jar
ENTRYPOINT ["java", "-jar", "/bitcoin-service.jar"]
EXPOSE 8444