FROM anapsix/alpine-java
MAINTAINER Vladimir Cvetanovic <cvetanovic9696@gmail.com>
ADD target/paypal-service-0.0.1-SNAPSHOT.jar paypal-service.jar
ENTRYPOINT ["java", "-jar", "/paypal-service.jar"]
EXPOSE 8443